import React from 'react';
import { ShieldCheck, Info } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Footer() {
  return (
    <footer className="border-t border-slate-200/80 bg-white/70 backdrop-blur-sm mt-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          {/* Brand Info */}
          <div className="md:col-span-2 space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-tealAccent flex items-center justify-center text-white">
                <ShieldCheck className="w-4 h-4" />
              </div>
              <span className="font-display font-bold text-lg text-ink">LoanSight</span>
            </div>
            <p className="text-ink-muted text-sm max-w-sm leading-relaxed">
              Production-grade Loan Default Prediction engine powered by Machine Learning trained on 255,000 anonymized loan application records.
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="font-display font-semibold text-ink text-sm uppercase tracking-wider mb-3">Navigation</h4>
            <ul className="space-y-2 text-sm text-ink-muted">
              <li><Link to="/" className="hover:text-tealAccent transition-colors">Home Landing</Link></li>
              <li><Link to="/predict" className="hover:text-tealAccent transition-colors">Assessment Wizard</Link></li>
              <li><Link to="/about" className="hover:text-tealAccent transition-colors">Model Specifications</Link></li>
            </ul>
          </div>

          {/* Legal / Disclaimer */}
          <div>
            <h4 className="font-display font-semibold text-ink text-sm uppercase tracking-wider mb-3">Disclaimer</h4>
            <div className="flex items-start gap-2 text-xs text-ink-muted bg-slate-100/80 p-3 rounded-xl border border-slate-200/60">
              <Info className="w-4 h-4 text-tealAccent shrink-0 mt-0.5" />
              <span>
                <strong>Educational project. Not financial advice.</strong> Predictions generated by this system are for academic demonstration purposes only.
              </span>
            </div>
          </div>
        </div>

        <div className="pt-6 border-t border-slate-200/60 flex flex-col sm:flex-row items-center justify-between text-xs text-ink-muted gap-4">
          <p>© {new Date().getFullYear()} LoanSight Analytics. All rights reserved.</p>
          <p className="font-mono text-[11px]">Model: GradientBoostingClassifier (150 trees)</p>
        </div>
      </div>
    </footer>
  );
}
